stages:
  - build

build-fedora:
  image: fedora:28
  stage: build
  before_script:
    - dnf -y install
        autoconf
        automake
        gettext-devel
        make
        which
        yelp-devel
        yelp-tools

  script:
    - ./autogen.sh
    - make -j
    - make -j check
    - make -j distcheck

  except:
    - tags
