stages:
  - build

build-fedora:
  image: fedora:28
  stage: build
  before_script:
    - dnf -y install
        autoconf
        automake
        glib2-devel
        make
        which
        yelp-devel
        yelp-tools

  script:
    - ./autogen.sh
    - make
    - make distcheck

  except:
    - tags
